swagger: '2.0'

info:
  title: User API
  version: "0.1.0"

paths:
  /ciserver/develop/merged:
    post:
      x-swagger-router-controller: gm_analytics
      operationId: handlers.develop_branch_merged
      summary: The develop branch has been merged.
      responses:
        200:
          description: Successful response.
          schema:
            type: object
            properties:
              command_return:
                type: string
                description: Merge action information.
